#define BEDCC_SGC
#define BEDCC_NORTTI
#define BEAR_ESP8266
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <ESP8266httpUpdate.h>
#include <EEPROM.h>
#include <Hash.h>
#include <ArduinoMqttClient.h>
