#include <iostream>
#include <memory>
#include <unordered_map>
#include <string>
#include <vector>
#include <cstdlib>
#include <limits>
#include <cstdint>
#include <sys/stat.h>
#include <stdio.h>
#include <chrono>
#include <thread>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <atomic>
#include <map>
#include <mutex>
#include <condition_variable>
#ifdef BEDCC_BGC
#define GC_THREADS
#include <gc.h>
#include <gc/gc_cpp.h>
#include <gc/gc_allocator.h>
#endif
